Add HTML Keyboard Slider Response
jspsych/jspsych-contrib pull request #118
Opened 2024-07-30 15:26 UTC by Max-Lovell

Adds a slider that accepts keypresses and a bunch of new parameters (maybe too many...). Updated Jest config to click continue button, and a few other things in there that can be commented out to check other features. A few examples are in the appropriate folder, too - all parameters listed. Let me know if clarifications needed.

2024-07-30 15:34 UTC, jodeleeuw commented
Thanks @Max-Lovell!

Would you be willing to fill out the documentation with the parameters?

2024-07-30 15:34 UTC, jodeleeuw commented
It'll also need a changeset

`npm run changeset` in the root directory.

2024-07-30 15:50 UTC, Max-Lovell commented
Hi Josh, thanks for the quick feedback - happy to add descriptions, although I thought these were created automatically? If so, perhaps I've screwed up the markdown but can't see where - can you point me in the right direction?

2024-07-30 15:56 UTC, jodeleeuw commented
Ah, we're moving in that direction, but it isn't quite done yet. You're welcome to leave as is, but it might be a couple of weeks before we have this all set up.

2024-07-31 08:30 UTC, Max-Lovell commented
Hi Josh, Ah okay then - all done! Thanks

2024-07-31 10:47 UTC, Max-Lovell commented
Note, implements suggestions from:
https://github.com/jspsych/jsPsych/issues/2570
https://github.com/jspsych/jsPsych/pull/2827

2024-08-01 19:47 UTC, jodeleeuw commented
One last thing - can you update the table in the main README for the repo to include the plugin? (hoping to automate this step in the future...)

2024-08-02 08:09 UTC, Max-Lovell commented
Sure - I actually forgot to do that last time. Listed my last contrib 'survey-slider' to the main list aswell, hopefully that's alright under this PR?

2024-08-02 14:20 UTC, jodeleeuw requested changes

2024-08-02 14:20 UTC, jodeleeuw commented on README.md
Can you put these in their alphabetical order spot?

2024-08-05 12:00 UTC, Max-Lovell commented on README.md
Done 👍

2024-08-05 12:07 UTC, merged

2024-08-05 12:14 UTC, Max-Lovell commented
Sorry, could you briefly reopen? I've noticed I put the wrong link in the list of packages: 
`https://github.com/jspsych/jspsych-contrib/blob/main/packages/plugin-html-keyboard-slider/docs/jspsych-html-keyboard-slider.md`
should be:
`https://github.com/jspsych/jspsych-contrib/blob/main/packages/plugin-html-keyboard-slider/docs/html-keyboard-slider.md`