Add function for flipping coherent dots in a trial
jspsych/jspsych-contrib pull request #147
Opened 2024-11-25 22:16 UTC by Hoboki

I made a function that flip the direction of coherent dots.

This function is similar one implemented in this study, where dots' directions are flipped probabilistically.
https://elifesciences.org/articles/08825

I also modified example1.html so you can check how it works.

Thank you in advance!

2024-12-09 12:49 UTC, Hoboki commented
Anyone can review this?

2025-01-11 19:26 UTC, Hoboki commented
Do I need to make new plugin? @jodeleeuw

2025-01-11 19:34 UTC, jodeleeuw commented
@jadeddelta if you have a chance to look at this. I will try soon!

2025-01-11 20:45 UTC, jadeddelta requested changes
looks good to me! just switch up the version bump type and i think we should be good to go

2025-01-11 20:45 UTC, jadeddelta commented on .changeset/odd-laws-sleep.md
> +"@jspsych-contrib/plugin-rdk": patch
we should probably make this a minor version bump, patch is usually reserved for bug fixes and minor is reserved for backwards-compatible feature releases like this

2025-01-11 22:00 UTC, Hoboki commented on .changeset/odd-laws-sleep.md
> +"@jspsych-contrib/plugin-rdk": patch
I've changed the version bump from patch into minor

2025-01-12 21:43 UTC, merged