Rok
jspsych/jspsych-contrib pull request #25
Opened 2022-04-05 16:39 UTC by younesStrittmatter

2022-04-05 21:10 UTC, jodeleeuw requested changes
Hi @younesStrittmatter. Thanks for submitting this! I've made some quick comments that deal mostly with the build/release process and getting things properly configured for that. Otherwise it looks great.

2022-04-05 21:10 UTC, jodeleeuw commented on packages/plugin-rok/CHANGELOG.md
> +# @jspsych-contrib/plugin-rok
This file should be deleted because it will be automatically generated by the release process.

2022-04-05 21:10 UTC, jodeleeuw commented on packages/plugin-rok/docs/jspsych-rok.md
> +<b>Strittmatter, Y., Spitzer, M., & Kiesel, A. (2021, July 12). A Random-Object-Kinematogram Plugin for Web-Based Research: Implementing Oriented Objects Enables Varying Coherence Levels and Stimulus
Can you use markdown instead of html for font styles?

Wrapping in ** will work

2022-04-05 21:10 UTC, jodeleeuw commented on packages/plugin-rok/docs/jspsych-rok.md
> +### Setting animated images as stimulus. Fade out images on the edges of the aperture. Mirror images instead of rotating them all the way (no upside down birds)
Looks like two titles for this section, or a missing example

2022-04-05 21:10 UTC, jodeleeuw commented on packages/plugin-rok/package.json
> +  "version": "1.0.0",
Drop this to version 0.1.0 so that the release process can automatically bump it to 1.0

2022-04-05 21:10 UTC, jodeleeuw commented on packages/plugin-rok/readme.md
> +import jsPsychRdk from '@jspsych-contrib/plugin-rok';
`jsPsychRok` instead?

2022-04-05 21:10 UTC, jodeleeuw commented on packages/plugin-rok/readme.md
> +Created by [Younes Strittmatter](https://github.com/younesStrittmatter), Hakwan Lau, and Brian Odegaard. Modified by the jsPsych core team for 7.0 compatibility.
Are Hakwan and Brian involved in this? Seems like something is off here.

2022-04-05 21:10 UTC, jodeleeuw commented on packages/plugin-rok/src/index.spec.ts
> +import rok from "../../../../packages/plugin-rok/src";
This path doesn't seem right.

2022-04-05 22:18 UTC, younesStrittmatter commented
Thank you a lot @jodeleeuw. I implemented the suggestions.

2022-04-06 14:15 UTC, jodeleeuw commented
I've added a changeset for the release workflow.

@younesStrittmatter lmk when you've finalized the feature set that you want in the initial release. I'll give it a quick test and then we can release it.

2022-04-18 18:35 UTC, younesStrittmatter commented
Hello @jodeleeuw,

I looked over the code and tested it locally. I think this version is redia for  a initial release. Thank you a lo for your input and the review.

2022-04-19 16:08 UTC, jodeleeuw commented
Hey @younesStrittmatter, 

I fixed the link to `jspsych.css` in the `example1.html` file. It looks like the example behaves weirdly after the first piece. Can you look it over and make sure that it is working as intended?

2022-04-19 19:03 UTC, younesStrittmatter commented
Hello @jodeleeuw,
I hope I have adressed the weird behaviour you were talking about. The prompts now show up at a correct spot, there is no flickering at the beginning of the rok with animated objects and after changing the tab or window the rok doesn't behave weird anymore.

2022-04-19 19:14 UTC, merged