image-array-keyboard-response-plugin
jspsych/jspsych-contrib pull request #58
Opened 2022-12-31 21:58 UTC by younesStrittmatter

show more than one image with specified positions and sizes

2023-01-03 17:47 UTC, younesStrittmatter commented
@jodeleeuw Thanks! This is ready to be reviewed.

2023-01-20 14:16 UTC, younesStrittmatter commented
@jodeleeuw Just a quick follow-up, in case you missed my last comment. This PR is ready to be reviewed

2023-01-20 14:26 UTC, jodeleeuw requested changes
I've flagged a few things to check/change. 

You'll also need to add a changeset to this PR so that our automated deploy system can publish it. You can follow the instructions that the bot posted above. It's pretty easy to do.

2023-01-20 14:26 UTC, jodeleeuw commented on packages/plugin-image-array-keyboard-response/docs/jspsych-image-array-keyboard-response.md
> +# jspsych-image-swipe-response plugin
title here needs to be updated

2023-01-20 14:26 UTC, jodeleeuw commented on packages/plugin-image-array-keyboard-response/docs/jspsych-image-array-keyboard-response.md
> +| keyboard_choices            | array of strings | `"NO_KEYS"` | This array contains the key(s) that the subject is allowed to press in order to respond to the stimulus. Keys should be specified as c
using `choices` instead of `keyboard_choices` would be more consistent with other plugins

2023-01-20 14:26 UTC, jodeleeuw commented on packages/plugin-image-array-keyboard-response/docs/jspsych-image-array-keyboard-response.md
> +        choices: ['f'],
this uses `choices` but the docs above say `keyboard_choices`

2023-01-20 14:26 UTC, jodeleeuw commented on packages/plugin-image-array-keyboard-response/examples/example1.html
> +        choices: ['f'], // valid key presses
same here

2023-01-20 14:26 UTC, jodeleeuw commented on packages/plugin-image-array-keyboard-response/package.json
> +  "private": "true",
this private flag needs to be removed for it to be published on npm

2023-01-20 14:26 UTC, jodeleeuw commented on packages/plugin-image-array-keyboard-response/readme.md
> +import jsPsychPluginName from '@jspsych-contrib/plugin-image-array-keyboard-response';
`jsPsychPluginName` should be `jsPsychImageArrayKeyboardResponse`

2023-01-20 14:26 UTC, jodeleeuw commented on packages/plugin-image-array-keyboard-response/src/index.ts
> + * @author Josh de Leeuw
can update this

2023-01-20 14:26 UTC, jodeleeuw commented on packages/plugin-image-array-keyboard-response/src/index.ts
> + * **image-keyboard-response**
change this to correct name

2023-01-20 14:26 UTC, jodeleeuw commented on packages/plugin-image-array-keyboard-response/src/index.ts
> + * jsPsych plugin for displaying an image stimulus and getting a keyboard response
update description here?

2023-01-20 14:26 UTC, jodeleeuw commented on packages/plugin-image-array-keyboard-response/src/index.ts
> + * @see {@link https://www.jspsych.org/plugins/jspsych-image-keyboard-response/ image-keyboard-response plugin documentation on jspsych.org}
update url?

2023-01-20 14:26 UTC, jodeleeuw commented on packages/plugin-rdk/package.json
> +  "dependencies": {
this file shouldn't be getting updated by your PR

2023-01-20 14:26 UTC, jodeleeuw commented on packages/plugin-rok/src/index.ts
> +         "applies to non-random oobs of main task. */
this file shouldn't get updated by this PR

2023-01-20 17:45 UTC, younesStrittmatter commented
@jodeleeuw Thanks for the review! I hope this implements them.

2023-01-23 21:03 UTC, jodeleeuw commented
thanks @younesStrittmatter! 

can you also update the main README file to include the plugin in the list?

2023-01-24 13:01 UTC, jodeleeuw approved these changes

2023-01-24 13:01 UTC, merged