Nextcloud filedrop plugin
jspsych/jspsych-contrib pull request #62
Opened 2023-02-02 15:53 UTC by mgrewe

Hi folks,

here is a pull request for a plugin for permanent data storage on a nextcloud instance that we developed for our experiments. It permits data upload to nextcloud via the [file drop](https://nextcloud.com/file-drop/) method. It is an alternative to the php/mysql combination proposed in the documentation.

If communication to nextcloud is TSL encrypted, this gives a secure and privacy compliant way to gather data. Only requirement is that the nextcloud instance is allowing Cross-Origin requests from the webhost. Please have a look at README.md for details.

Cheers
Martin

PS: I still did not manage to pack JSZip into the build. I think for usability it would be good to provide a bundled lib. Can you please help me out with this? Thanks

2023-02-20 19:55 UTC, bjoluc commented
Hi @mgrewe,

thanks for sharing!

> I still did not manage to pack JSZip into the build. I think for usability it would be good to provide a bundled lib. Can you please help me out with this? Thanks

Dependencies are only bundled when your plugin is built by the full build chain, i.e., when using the [TypeScript template](https://github.com/jspsych/jspsych-contrib/tree/main/packages/plugin-template-ts). Feel free to migrate to TS or let us know if you'd like the PR to be merged as-is :+1:

2023-03-07 15:39 UTC, jodeleeuw requested changes

2023-03-07 15:39 UTC, jodeleeuw commented on packages/plugin-nextcloud-filedrop/package.json
> +  "private": "true",
This flag will need to be removed before it can be published

2023-03-07 15:39 UTC, jodeleeuw commented on packages/plugin-nextcloud-filedrop/package.json
> +    "directory": "packages/plugin-moot"
this directory should be updated

2023-03-12 19:20 UTC, mgrewe commented
Thanks @jodeleeuw. All fixed now. Cheers

2023-04-04 18:41 UTC, jodeleeuw approved these changes

2023-04-04 18:46 UTC, merged