Adding IOS plugin
jspsych/jspsych-contrib pull request #71
Opened 2023-06-06 14:39 UTC by kinleyid

This is a plugin for the Integration of Other in the Self (IOS) Scale. A demonstration can be seen here: https://kinleyid.github.io/rsrch/jspsych-ios/examples/classic.html. Please let me know if anything else is needed to add this to jspsych-contrib! Thanks.

2023-06-06 16:23 UTC, jodeleeuw requested changes
Thanks @kinleyid for another contribution! 🥳 

In addition to the minor changes I've noted in the code, please:

- [ ] Add a changeset, marking it as a major release
- [ ] Update the README.md file in the root of jspsych-contrib to link to the new plugin.

2023-06-06 16:23 UTC, jodeleeuw commented on packages/plugin-ios/package.json
> +  "version": "1.0.0",
This should be 0.0.1 so that the release action can autobump to 1.0.0

2023-06-06 16:23 UTC, jodeleeuw commented on packages/plugin-ios/index.js
> +  class jsPsychHtmlVasResponsePlugin {
The class name should probably be changed

2023-06-06 16:23 UTC, jodeleeuw commented on packages/plugin-ios/index.js
> +  return jsPsychHtmlVasResponsePlugin;
class name here as well

2023-06-06 16:23 UTC, jodeleeuw commented on packages/plugin-ios/README.md
> +See [documentation](docs/jspsych-html-vas-response.md)
link here should be updated

2023-06-06 18:30 UTC, kinleyid commented
Thanks for catching those! I've made the requested changes.

2023-06-06 19:52 UTC, jodeleeuw commented
Can you also update the README.md in the root of jspsych-contrib to add a link and description of the plugin? Then I think we are good to go!

2023-06-07 12:22 UTC, kinleyid commented
Done!

2023-06-07 14:08 UTC, jodeleeuw approved these changes

2023-06-07 14:08 UTC, merged

2023-06-07 14:23 UTC, jodeleeuw commented
This is now published on npm. Thanks again @kinleyid!