New gamepad plugin
jspsych/jspsych-contrib pull request #82
Opened 2023-12-05 00:59 UTC by Shaobin-Jiang

Using gamepads in experiments is sometimes needed, and while most browsers support it, a certain tweaking around is still needed. This plugin handles input from a gamepad and displays a minature model on the page that reflects user input in real time for the convenience of debugging.

2023-12-05 16:33 UTC, jodeleeuw requested changes
Thanks for the contribution @Shaobin-Jiang! 

I left one small tweak to make to get the plugin to publish in the correct npm location.

2023-12-05 16:33 UTC, jodeleeuw commented on packages/plugin-gamepad/package.json
> +  "name": "@Shaobin-Jiang/jspsych-gamepad",
To publish this in our npm namespace this should be `"@jspsych-contrib/plugin-gamepad"`

2023-12-20 16:57 UTC, merged

2023-12-20 16:57 UTC, jodeleeuw commented
Thank you @Shaobin-Jiang !

2023-12-20 16:58 UTC, jodeleeuw commented
Reverted this because I missed the lack of a changeset. Will fix.

2023-12-20 17:13 UTC, jodeleeuw commented
Sorry @Shaobin-Jiang -- can you make a new PR? I should've checked more carefully first and just added the changeset as a separate commit. Can you also target `@jspsych/config` v2 in `package.json`?

2023-12-20 18:19 UTC, bjoluc commented
@jodeleeuw Technically, we can also add a changeset for a specific PR after merging it thanks to https://github.com/changesets/changesets/pull/535 :+1:

2023-12-20 20:22 UTC, jodeleeuw commented
oops. good to know, thank you!

2023-12-21 04:50 UTC, Shaobin-Jiang commented
@jodeleeuw Done in #86